/**
 * WhatsApp share functionality for Loan Checklist
 * Opens WhatsApp with checklist items as message text
 */

interface ShareOptions {
  loanType: string;
  items: { name: string; category: string; required: boolean }[];
  title?: string;
}

/**
 * Get loan type display name from loan type code
 */
function getLoanTypeLabel(loanType: string): string {
  const labels: Record<string, string> = {
    home_loan: 'Home Loan',
    lap: 'Loan Against Property (LAP)',
    mudra: 'Mudra Loan',
    msme: 'MSME Loan',
    business_loan: 'Business Loan',
    personal_loan: 'Personal Loan',
    education_loan: 'Education Loan',
  };
  return labels[loanType] || loanType;
}

/**
 * Get category display name
 */
function getCategoryLabel(category: string): string {
  const labels: Record<string, string> = {
    kyc: 'KYC Documents',
    income_proof: 'Income Proof',
    business_documents: 'Business Documents',
    property_documents: 'Property Documents',
    financial_documents: 'Financial Documents',
    legal_documents: 'Legal Documents',
  };
  return labels[category] || category;
}

/**
 * Share checklist on WhatsApp
 * Uses WhatsApp Web API (wa.me) with text parameter
 * Falls back to Web Share API on mobile devices
 */
export async function shareOnWhatsApp(options: ShareOptions): Promise<boolean> {
  const { loanType, items, title } = options;

  if (items.length === 0) {
    console.warn('Cannot share empty checklist');
    return false;
  }

  // Group items by category for organized sharing
  const groupedItems: Record<string, typeof items> = {};
  items.forEach((item) => {
    const category = getCategoryLabel(item.category);
    if (!groupedItems[category]) {
      groupedItems[category] = [];
    }
    groupedItems[category].push(item);
  });

  // Build the share text
  const lines: string[] = [];
  lines.push(`📋 *${title || `Loan Checklist - ${getLoanTypeLabel(loanType)}`}*`);
  lines.push('');
  lines.push(title ? 'Pending Documents:' : 'Required Documents:');
  lines.push('');

  Object.entries(groupedItems).forEach(([category, categoryItems]) => {
    lines.push(`*${category}:*`);
    categoryItems.forEach((item) => {
      const requiredMark = item.required ? '' : ' (Optional)';
      lines.push(`• ${item.name}${requiredMark}`);
    });
    lines.push('');
  });

  lines.push('---');
  lines.push('Generated by InstaFin Portal');

  const text = encodeURIComponent(lines.join('\n'));

  // Try WhatsApp Web first
  const whatsappUrl = `https://wa.me/?text=${text}`;

  // Check if Web Share API is available (mobile devices)
  if (navigator.share && /Mobi|Android/i.test(navigator.userAgent)) {
    try {
      await navigator.share({
        title: `Loan Checklist - ${getLoanTypeLabel(loanType)}`,
        text: lines.join('\n'),
      });
      return true;
    } catch (err) {
      // User cancelled or share failed, try WhatsApp as fallback
      console.log('Web Share failed, trying WhatsApp:', err);
    }
  }

  // Open WhatsApp Web
  window.open(whatsappUrl, '_blank');
  return true;
}

/**
 * Check if Web Share API is available (for UI conditional rendering)
 */
export function isWebShareAvailable(): boolean {
  return typeof navigator.share === 'function';
}